### ISSUE TITLE
Review Notes Page

### ISSUE THREAD

**Issue by mrjoh3** [djpr-data/djprtradedash#99]
need to review the content on the Notes tab ensuring there is

1. clear info on data source and parameters 
2. caveats around usage to avoid any liability or unintentional misuse by businesses

**Comment by mrjoh3** [comment]
@Emma-DJPR Beau has been called into other work this week, so I am assigning this to your

**Comment by Emma-DJPR** [comment]
The note has all the information necessary for users.   The important points are explained in detail and directed on the ABS website if required.  The source for each chart is cited except for Merchandise Exports Data Explorer visualisation. I don't think we need to have additional caveats since we are using publicly available data.
